const translations = {
  he: { dir:"rtl", home:"דף הבית", services:"עסקים נותני שירות", governmentBodies:"גופים ממשלתיים וציבוריים", dashboard:"לוח בקרה", admin:"ניהול", shop:"החנות של אלון", cart:"עגלה", login:"כניסה", logout:"יציאה", about:"אודות", contact:"צור קשר", whatsapp:"כתיבה ב-WhatsApp", phone:"טלפון", menu:"תפריט", subtitle:"מרכז שירותים לאנשים עם מוגבלות" },
  en: { dir:"ltr", home:"Home", services:"Service Providers", governmentBodies:"Government & Public Bodies", dashboard:"Dashboard", admin:"Admin", shop:"Alon's Shop", cart:"Cart", login:"Login", logout:"Logout", about:"About", contact:"Contact", whatsapp:"Write on WhatsApp", phone:"Phone", menu:"Menu", subtitle:"Service center for people with disabilities" },
  ru: { dir:"ltr", home:"Главная", services:"Поставщики услуг", governmentBodies:"Государственные и общественные организации", dashboard:"Панель", admin:"Управление", shop:"Магазин Алона", cart:"Корзина", login:"Вход", logout:"Выход", about:"О нас", contact:"Контакты", whatsapp:"Написать в WhatsApp", phone:"Телефон", menu:"Меню", subtitle:"Центр услуг для людей с инвалидностью" },
  ar: { dir:"rtl", home:"الرئيسية", services:"مقدمو الخدمات", governmentBodies:"الجهات الحكومية والعامة", dashboard:"لوحة التحكم", admin:"الإدارة", shop:"متجر ألون", cart:"السلة", login:"دخول", logout:"خروج", about:"من نحن", contact:"اتصل بنا", whatsapp:"اكتب عبر WhatsApp", phone:"هاتف", menu:"القائمة", subtitle:"مركز خدمات للأشخاص ذوي الإعاقة" },
  am: { dir:"ltr", home:"መነሻ", services:"አገልግሎት ሰጪዎች", governmentBodies:"የመንግስትና የህዝብ ተቋማት", dashboard:"ፓነል", admin:"አስተዳደር", shop:"የአሎን ሱቅ", cart:"ጋሪ", login:"መግቢያ", logout:"ውጣ", about:"ስለ እኛ", contact:"ያግኙን", whatsapp:"በWhatsApp ይጻፉ", phone:"ስልክ", menu:"ምናሌ", subtitle:"ለአካል ጉዳተኞች የአገልግሎት ማዕከል" },
  fr: { dir:"ltr", home:"Accueil", services:"Prestataires de services", governmentBodies:"Organismes publics et gouvernementaux", dashboard:"Tableau de bord", admin:"Administration", shop:"Boutique d'Alon", cart:"Panier", login:"Connexion", logout:"Déconnexion", about:"À propos", contact:"Contact", whatsapp:"Écrire sur WhatsApp", phone:"Téléphone", menu:"Menu", subtitle:"Centre de services pour les personnes handicapées" },
  fil: { dir:"ltr", home:"Home", services:"Mga Service Provider", governmentBodies:"Mga Ahensya ng Pamahalaan at Publiko", dashboard:"Dashboard", admin:"Admin", shop:"Tindahan ni Alon", cart:"Cart", login:"Login", logout:"Logout", about:"Tungkol sa Amin", contact:"Makipag-ugnayan", whatsapp:"Sumulat sa WhatsApp", phone:"Telepono", menu:"Menu", subtitle:"Sentro ng serbisyo para sa mga taong may kapansanan" },
  hi: { dir:"ltr", home:"मुखपृष्ठ", services:"सेवा प्रदाता", governmentBodies:"सरकारी और सार्वजनिक संस्थाएँ", dashboard:"डैशबोर्ड", admin:"प्रशासन", shop:"अलोन की दुकान", cart:"कार्ट", login:"लॉगिन", logout:"लॉगआउट", about:"हमारे बारे में", contact:"संपर्क", whatsapp:"WhatsApp पर लिखें", phone:"फ़ोन", menu:"मेनू", subtitle:"विकलांग लोगों के लिए सेवा केंद्र" }
};

export default translations;
