import { useCallback,useEffect,useMemo,useState } from "react";
import { Link } from "react-router-dom";
import "./AdminApps.css";
const API=(process.env.REACT_APP_API_BASE||"https://alonpc02026.onrender.com/api")+"/apps";
const PLATFORMS=[['android','🤖 Android / Galaxy'],['ios','🍎 iPhone / iOS'],['windows','🪟 Windows 10–11'],['mac','💻 Mac'],['tv','📺 טלוויזיה חכמה']];
const EMPTY={name:'',description:'',publisher:'',platform:'android',imageUrl:'',url:'',active:true};
export default function AdminApps(){const[apps,setApps]=useState([]),[form,setForm]=useState(EMPTY),[editingId,setEditingId]=useState(''),[message,setMessage]=useState(''),[search,setSearch]=useState('');
 const load=useCallback(async()=>{try{const r=await fetch(`${API}?admin=true`);const d=await r.json().catch(()=>[]);if(!r.ok)throw new Error(d.message||'טעינה נכשלה');setApps(Array.isArray(d)?d:d.apps||[])}catch(e){setMessage(`❌ ${e.message}`)}},[]);useEffect(()=>{load()},[load]);
 const update=(k,v)=>setForm(f=>({...f,[k]:v})); const reset=()=>{setForm(EMPTY);setEditingId('')};
 const edit=a=>{setEditingId(a._id);setForm({name:a.name||a.title||'',description:a.description||'',publisher:a.publisher||'',platform:a.platform||a.type||a.deviceType||'android',imageUrl:a.imageUrl||a.logoUrl||'',url:a.url||a.websiteUrl||a.storeUrl||'',active:a.active!==false});window.scrollTo({top:0,behavior:'smooth'})};
 const save=async e=>{e.preventDefault();if(!form.name.trim())return setMessage('❌ חובה להזין שם');try{const payload={...form,type:form.platform,deviceType:form.platform};const r=await fetch(editingId?`${API}/${editingId}`:API,{method:editingId?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||'שמירה נכשלה');setMessage('✅ נשמר בהצלחה');reset();await load()}catch(err){setMessage(`❌ ${err.message}`)}};
 const remove=async a=>{if(!window.confirm(`למחוק את ${a.name||a.title}?`))return;const r=await fetch(`${API}/${a._id}`,{method:'DELETE'});if(r.ok){setMessage('🗑️ נמחק');load()}};
 const filtered=useMemo(()=>apps.filter(a=>!search||`${a.name||''} ${a.platform||a.type||''}`.toLowerCase().includes(search.toLowerCase())),[apps,search]);
 return <main className="aa-page" dir="rtl"><header className="aa-head"><div><h1>📱 ניהול אפליקציות</h1><p>חובה לבחור לכל אפליקציה Android או iPhone או מערכת אחרת.</p></div><Link to="/admin">חזרה לניהול</Link></header>{message&&<div className="aa-msg">{message}</div>}<form className="aa-form" onSubmit={save}><h2>{editingId?'עריכת אפליקציה':'הוספת אפליקציה'}</h2><div className="aa-grid"><label>שם *<input value={form.name} onChange={e=>update('name',e.target.value)} required/></label><label>מערכת הפעלה *<select value={form.platform} onChange={e=>update('platform',e.target.value)}>{PLATFORMS.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>מפתח<input value={form.publisher} onChange={e=>update('publisher',e.target.value)}/></label><label>קישור<input value={form.url} onChange={e=>update('url',e.target.value)} placeholder="https://"/></label><label className="wide">תמונה<input value={form.imageUrl} onChange={e=>update('imageUrl',e.target.value)} placeholder="https://"/></label><label className="wide">תיאור<textarea rows="4" value={form.description} onChange={e=>update('description',e.target.value)}/></label></div><button type="submit">💾 שמירה</button>{editingId&&<button type="button" onClick={reset}>ביטול</button>}</form><section className="aa-list"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="🔎 חיפוש..."/>{filtered.map(a=><article key={a._id}><strong>{a.name||a.title}</strong><span>{PLATFORMS.find(([v])=>v===(a.platform||a.type||a.deviceType))?.[1]||'⚠️ לא משויך'}</span><button onClick={()=>edit(a)}>✏️ עריכה</button><button className="del" onClick={()=>remove(a)}>🗑️</button></article>)}</section></main>}
