import { useEffect, useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import "./AppsCategory.css";

const API=(process.env.REACT_APP_API_BASE||"https://alonpc02026.onrender.com/api")+"/apps";
const META={android:{title:"Android / Galaxy",icon:"🤖",aliases:["android","galaxy","samsung"]},ios:{title:"iPhone / iOS",icon:"🍎",aliases:["ios","iphone","apple"]},windows:{title:"Windows 10–11",icon:"🪟",aliases:["windows","windows10","windows11","pc"]},mac:{title:"Mac",icon:"💻",aliases:["mac","macos"]},tv:{title:"טלוויזיה חכמה",icon:"📺",aliases:["tv","smart-tv","smarttv"]}};
const norm=v=>String(v||"").trim().toLowerCase().replace(/\s+/g,"-");
export default function AppsCategory(){
 const {type}=useParams(); const key=norm(type); const meta=META[key]||{title:type||"אפליקציות",icon:"📱",aliases:[key]};
 const [apps,setApps]=useState([]),[search,setSearch]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{let active=true;(async()=>{try{const r=await fetch(API);const d=await r.json().catch(()=>[]);if(!r.ok)throw new Error(d.message||"לא ניתן לטעון אפליקציות");if(active)setApps(Array.isArray(d)?d:d.apps||[])}catch(e){if(active)setError(e.message)}finally{if(active)setLoading(false)}})();return()=>{active=false}},[]);
 const filtered=useMemo(()=>apps.filter(a=>{const p=norm(a.platform||a.type||a.deviceType||a.os);const txt=[a.name,a.title,a.description,a.publisher].filter(Boolean).join(" ").toLowerCase();return meta.aliases.includes(p)&&(!search||txt.includes(search.toLowerCase()))}),[apps,search,meta.aliases]);
 return <main className="apps-category-page" dir="rtl"><header className="apps-category-hero"><span>{meta.icon}</span><div><h1>{meta.title}</h1><p>מוצגות רק אפליקציות ששויכו למערכת הזו.</p></div></header><section className="apps-category-tools"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={`🔎 חיפוש בתוך ${meta.title}...`}/><Link to="/apps/mobile">📱 חזרה לאפליקציות סלולרי</Link></section>{loading&&<p className="apps-category-status">טוען...</p>}{error&&<p className="apps-category-status error">{error}</p>}{!loading&&!error&&filtered.length===0&&<section className="apps-category-status"><b>אין כרגע אפליקציות משויכות ל-{meta.title}</b><p>ערוך את האפליקציה בניהול ובחר מערכת הפעלה מתאימה.</p></section>}<section className="apps-category-grid">{filtered.map(a=><article className="app-card" key={a._id||a.id||a.name}><div className="app-card-image">{a.imageUrl||a.logoUrl?<img src={a.imageUrl||a.logoUrl} alt={a.name||a.title||""}/>:<span>{meta.icon}</span>}</div><div className="app-card-body"><h2>{a.name||a.title}</h2>{a.description&&<p>{a.description}</p>}{(a.url||a.websiteUrl||a.storeUrl)&&<a href={a.url||a.websiteUrl||a.storeUrl} target="_blank" rel="noreferrer">פתיחת האפליקציה / החנות</a>}</div></article>)}</section></main>
}
