import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import "./Services.css";
const API_BASE=process.env.REACT_APP_API_BASE||(window.location.hostname==="localhost"||window.location.hostname==="127.0.0.1"?"http://localhost:3001/api":"https://alonpc02026.onrender.com/api");
const DAYS=[["sunday","יום ראשון"],["monday","יום שני"],["tuesday","יום שלישי"],["wednesday","יום רביעי"],["thursday","יום חמישי"],["friday","יום שישי"],["saturday","יום שבת"]];
const whatsappUrl=n=>{const d=String(n||"").replace(/\D/g,"");return d?`https://wa.me/${d.startsWith("0")?`972${d.slice(1)}`:d}`:""};
const Hours=({hours,note})=>{const rows=DAYS.filter(([k])=>hours?.[k]?.enabled);if(!rows.length&&!note)return null;return <section className="opening-hours-public"><h3>🕒 ימים ושעות פתיחה</h3>{rows.map(([k,l])=><p key={k}><strong>{l}:</strong> {hours[k].open}–{hours[k].close}</p>)}{note&&<p className="hours-note">ℹ️ {note}</p>}</section>};
export default function Services(){const[services,setServices]=useState([]),[search,setSearch]=useState(""),[category,setCategory]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");useEffect(()=>{fetch(`${API_BASE}/services?active=true`).then(async r=>{const d=await r.json().catch(()=>[]);if(!r.ok)throw new Error("לא ניתן לטעון שירותים");setServices(Array.isArray(d)?d:[])}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);const categories=useMemo(()=>[...new Set(services.map(i=>i.category).filter(Boolean))].sort(),[services]);const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return services.filter(i=>(!q||`${i.name} ${i.businessName} ${i.category} ${i.city} ${i.description}`.toLowerCase().includes(q))&&(!category||i.category===category))},[services,search,category]);return <main className="services-accessible-page" dir="rtl"><header><h1>מאגר שירותים נגישים</h1><p>חיפוש עסקים ושירותים התומכים באנשים עם מוגבלות.</p></header><section className="services-accessible-filters"><input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="חיפוש שירות, עסק או עיר"/><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">כל הקטגוריות</option>{categories.map(c=><option key={c}>{c}</option>)}</select></section>{loading&&<p className="services-accessible-status">טוען...</p>}{error&&<p className="services-accessible-status error">{error}</p>}<section className="services-accessible-grid">{filtered.map(i=><article key={i._id}>{(i.imageUrl||i.logoUrl)&&<img src={i.imageUrl||i.logoUrl} alt={i.name}/>}<div><h2>{i.name}</h2><p className="category">{i.category}</p>{i.businessName&&<p><strong>שם העסק:</strong> {i.businessName}</p>}{i.description&&<p className="description">{i.description}</p>}<p className="location">📍 {i.city||"ללא עיר"} {i.address&&`· ${i.address}`}</p><Hours hours={i.openingHours} note={i.openingHoursNote}/>{i.phone&&<a className="phone" href={`tel:${i.phone}`}>📱 {i.phone}</a>}{i.acceptsWhatsApp&&i.whatsapp&&<a className="contact-button whatsapp" href={whatsappUrl(i.whatsapp)} target="_blank" rel="noreferrer">🟢 WhatsApp</a>}{i.acceptsEmail&&i.email&&<a className="contact-button email" href={`mailto:${i.email}`}>✉️ דואר אלקטרוני</a>}<div className="social-links" aria-label="רשתות חברתיות וניווט">
{i.hasInstagram&&i.instagramUrl&&<a className="social-button instagram" href={i.instagramUrl} target="_blank" rel="noreferrer" aria-label={`Instagram של ${i.businessName||i.name}`}>📸 Instagram</a>}
{i.hasFacebook&&i.facebookUrl&&<a className="social-button facebook" href={i.facebookUrl} target="_blank" rel="noreferrer" aria-label={`Facebook של ${i.businessName||i.name}`}>📘 Facebook</a>}
{i.hasTikTok&&i.tiktokUrl&&<a className="social-button tiktok" href={i.tiktokUrl} target="_blank" rel="noreferrer" aria-label={`TikTok של ${i.businessName||i.name}`}>🎵 TikTok</a>}
{i.hasWaze&&i.wazeUrl&&<a className="social-button waze" href={i.wazeUrl} target="_blank" rel="noreferrer" aria-label={`ניווט Waze אל ${i.businessName||i.name}`}>🚗 Waze</a>}
</div><div className="actions"><Link to={`/service/${i._id}`}>פרטי השירות</Link>{(i.link||i.websiteUrl)&&<a href={i.link||i.websiteUrl} target="_blank" rel="noreferrer">מעבר לעסק</a>}</div></div></article>)}</section></main>}
